apiVersion: v1
kind: Service
metadata:
  labels:
    app: krampoline
  name: krampoline
spec:
  ports:
    - name: 8080-8080
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: krampoline
  type: LoadBalancer